apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: wKcSpDG9DR1Rxv28OaJecYWlj39VtQTZecD6BtgoZ5+7pHQiStVpVw/DHWdZOTJIWXmYK3AR5wSlVsR1sxB1ifdrH8kdL+sWYmqMnBMWQQbU4x2ONbjGyTHS8b1oo2CoT/D/08pA/HwxYLnBQJIEgOk3P4TnbYqcD0m6Y4PjgmjImJ4YQwUvzbpoVt/8sAeh4BGCVc+TigbsM0mp2X1Ai4Dk55Ar2+ZS8CiQv0NfGg0/232HvPYpc9SIyg/yxs/jZMqJj3BU4/BcAg+HHh5udQhkqKC1jFI6mJ57hAhb3fM6IQlrN74Nu3OMBlwztx5QZV2NzV59dJpqlRAyGkNVFowJsfXYbHesy0rJCkaYkD26Z7KXcwQiXMf8kx2ngHbzFJMBIO3bGVKu4s9a/2JAGgHu2K+DX5E3RujJEczy6zrBzmkPR/D2znS88FSOW+0MmBM60pENe3d4qQjE69lM6ZB1dZDHg+uNREop0j8HxaF87XvzLtXuDnKHbP87RcQw0DZjL4f3egfGIHVlTlHIpA==
    server: https://192.0.2.1:6443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    namespace: test-namespace
    user: test-sa
  name: test-context
current-context: test-context
kind: Config
users:
- name: test-sa
  user:
    token: eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImZha2VrZXkxMjMifQ.eyJpc3MiOiAia3ViZXJuZXRlcy9zZXJ2aWNlYWNjb3VudCIsICJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L25hbWVzcGFjZSI6ICJ0ZXN0LW5hbWVzcGFjZSIsICJzdWIiOiAic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRlc3QtbmFtZXNwYWNlOnRlc3Qtc2EifQ.eJMkiOHubVS_AOMJl5_Fps_d1Vp_h64sVcKQ1W3R28H0FwGHvXdu30bXPq8Wr6nua-H-RJazdrIRt1tXtF7yWeNfXsnNOuvuwiPJFO5jIvi6ZioJ1qbO1lfNInKumdTuueQvEW1dKtHgyAl9Z528qw4APyyaWMIsoHZ2aXz8xRo6bf-GVWKY07eGb1Se04Hw1u2HpNWDOruCTsmgRMhiEXgrH5-0lZqC_r1WllK8Ji1Z1a6UM_GRR3HNB2pSRqGfdUit2_LOmHRVkDrEIBiiA0cqZZ_Lz7it49QF2Z0MYeu11tR6kI8bgYwnOsMYYWHVNvHuV0yFH9oYVsfUHX-ReA
